#writes cif coordinates to fname
function writecif(fname,atoms,coords,latvec)

  lenang = latvec2lenang(latvec);
  natoms = size(coords,1);
  GC = mean(coords,1);
  coords -= GC;
  internal = coords*inv(latvec');
  
  fid = fopen(fname,"w");
  fprintf(fid,'data_block_1\n');
  fprintf(fid,['_audit_creation_date         ''',datestr(now,'ddd mmm dd HH:MM:SS yyyy'),'''\n']);
  fprintf(fid,'_audit_creation_method       ''generated by writecif''\n');
  fprintf(fid,'\n\n');
  fprintf(fid,'_cell_length_a           %9.4f\n',lenang(1));
  fprintf(fid,'_cell_length_b           %9.4f\n',lenang(2));
  fprintf(fid,'_cell_length_c           %9.4f\n',lenang(3));
  fprintf(fid,'_cell_angle_alpha        %7.2f\n',lenang(4));
  fprintf(fid,'_cell_angle_beta         %7.2f\n',lenang(5));
  fprintf(fid,'_cell_angle_gamma        %7.2f\n',lenang(6));
  fprintf(fid,'\n\n');
  fprintf(fid,'_symmetry_space_group_name_H-M   ''P 1''\n');
  fprintf(fid,'_symmetry_Int_Tables_number       1\n');
  fprintf(fid,'\n\n');
  fprintf(fid,'loop_\n');
  fprintf(fid,'_atom_site_label\n');
  fprintf(fid,'_atom_site_fract_x\n');
  fprintf(fid,'_atom_site_fract_y\n');
  fprintf(fid,'_atom_site_fract_z\n');
  
  for i=1:natoms,
    fprintf(fid,'%2s %9.4f %9.4f %9.4f\n',atoms{i},internal(i,:));
  endfor
  fprintf(fid,'\n\n\n');
  
  fclose(fid);

endfunction